/** Single source of truth for the library and game loader. */
window.ArcadeCatalog = Object.freeze([
    { id: 'snake', title: 'Neon Snake', category: 'Arcade', mode: 'Four arenas', description: 'Find your rhythm with buffered turns, fruit bonuses and four arenas.', keywords: '贪吃蛇 neon snake', screen: 'snake-screen', script: 'snake.js', init: 'initSnakeGame', legacy: 'switchToSnake', cover: 0 },
    { id: 'tetris', title: 'Prismatic Tetris', category: 'Arcade', mode: 'High score', description: 'Four modes, satisfying combos and an AI that plays alongside you.', keywords: '俄罗斯方块 blocks', screen: 'tetris-screen', script: 'tetris.js', init: 'initTetrisGame', legacy: 'switchToTetris', cover: 1 },
    { id: '2048', title: '2048 Puzzle', category: 'Puzzle', mode: 'Save & resume', description: 'Slide, combine and rethink a move with undo and saved boards.', keywords: '数字 合成', screen: 'game2048-screen', script: '2048.js', init: 'init2048Game', legacy: 'switchTo2048', cover: 2 },
    { id: 'sudoku', title: 'Prism Sudoku', category: 'Puzzle', mode: 'Relax', description: 'Find your flow with Classic and Killer Sudoku.', keywords: '数独 logic', screen: 'sudoku-screen', script: 'sudoku.js', init: 'initSudokuGame', legacy: 'switchToSudoku', cover: 3 },
    { id: 'shooter', title: 'Neon Shooter', category: 'Arcade', mode: 'Space adventure', description: 'Five sectors, powerful bosses and endless waves to master.', keywords: '射击 飞机 space', screen: 'shooter-screen', script: 'shooter.js', init: 'initShooterGame', legacy: 'switchToShooter', cover: 4 },
    { id: 'merge10', title: 'Merge 10 · 合成10', category: 'Puzzle', mode: 'Beat the clock', description: 'Find rectangles that add up to ten. Every second counts.', keywords: '合十 消除 ten numbers', screen: 'merge10-screen', script: 'merge10.js', init: 'initMerge10Game', legacy: 'switchToMerge10', cover: 5 },
    { id: 'coin', title: 'Lucky Coin Toss', category: 'Arcade', mode: 'Ten-flip challenge', description: 'Make a call and test your predictions in a quick ten-round challenge.', keywords: '抛硬币 casual', screen: 'coin-screen', script: 'coin.js', init: 'initCoinGame', legacy: 'switchToCoin', cover: 6 },
    { id: 'chess', title: 'Chess', category: 'Strategy', mode: 'AI or a friend', description: 'Plan your next move with full chess rules and three AI levels.', keywords: '国际象棋 board pvp', screen: 'chess-screen', script: 'chess.js', init: 'initChessGame', legacy: 'switchToChess', cover: 7 },
    { id: 'gomoku', title: 'Five in a Row', category: 'Strategy', mode: 'AI or a friend', description: 'A simple board. Endless possibilities. Connect five to win.', keywords: '五子棋 gomoku board pvp', screen: 'gomoku-screen', script: 'gomoku.js', init: 'initGomokuGame', legacy: 'switchToGomoku', cover: 8 },
    { id: 'xiangqi', title: 'Chinese Chess', category: 'Strategy', mode: 'AI or a friend', description: 'Cross the river and challenge an opponent in classic Xiangqi.', keywords: '中国象棋 将帅 xiangqi board pvp', screen: 'xiangqi-screen', script: 'xiangqi.js', init: 'initXiangqiGame', legacy: 'switchToXiangqi', cover: 9 },
    { id: 'poker', title: 'Texas Hold’em Odds', category: 'Tools', mode: 'Odds calculator', description: 'Explore the probabilities behind any hand of Texas Hold’em.', keywords: '德州扑克 poker simulator cards', screen: 'poker-screen', script: 'poker.js', init: 'initPokerGame', legacy: 'switchToPoker', cover: 10 },
    { id: 'ten-helper', title: 'Merge 10 Solver', category: 'Tools', mode: 'Step-by-step', description: 'Edit a board, find a route and replay every move at your own pace.', keywords: '合十消除助手 合成10 solver ocr helper', screen: 'ten-helper-screen', script: 'merge10.js', init: 'initTenHelper', legacy: 'switchToTenHelper', cover: 11 },
]);
